(WIP): Upgrade GameServer project to VS022
Upgraded the GameServer project to vs2022.
Some DbgOut function commeted temporarily, need to fix it (ERROR C3861)